module.exports.supportedPlatforms = [
  { name: "Facebook", regex: /(?:www\.)?(?:facebook\.com|m\.facebook\.com|fb\.com|fb\.watch)/i },
  { name: "Instagram", regex: /(?:www\.)?instagram\.com/i },
  { name: "Twitter/X", regex: /(?:www\.)?(?:twitter\.com|x\.com)/i },
  { name: "Youtube", regex: /(?:www\.)?(?:youtube\.com|youtu\.be)/i },
  { name: "Tiktok", regex: /(?:www\.)?(?:tiktok\.com|vm\.tiktok\.com)/i },
  { name: "Reddit", regex: /(?:www\.)?reddit\.com/i },
  { name: "Pinterest", regex: /(?:www\.)?pinterest\.com/i },
  { name: "Linkedin", regex: /(?:www\.)?linkedin\.com/i },
  { name: "Tumblr", regex: /(?:www\.)?tumblr\.com/i },
  { name: "Vimeo", regex: /(?:www\.)?vimeo\.com/i },
  { name: "Snapchat", regex: /(?:www\.)?snapchat\.com/i },
  { name: "Bilibili", regex: /(?:www\.)?bilibili\.com/i },
  { name: "Dailymotion", regex: /(?:www\.)?dailymotion\.com/i },
  { name: "Soundcloud", regex: /(?:www\.)?soundcloud\.com/i },
  { name: "Spotify", regex: /(?:www\.)?spotify\.com/i },
  { name: "Deezer", regex: /(?:www\.)?deezer\.com/i },
  { name: "Bandcamp", regex: /(?:www\.)?bandcamp\.com/i },
  { name: "Mixcloud", regex: /(?:www\.)?mixcloud\.com/i },
  { name: "Bluesky", regex: /(?:www\.)?bsky\.app/i },
  { name: "Threads", regex: /(?:www\.)?threads\.net/i },
  { name: "Douyin", regex: /(?:www\.)?douyin\.com/i },
  { name: "Kuaishou", regex: /(?:www\.)?kuaishou\.com/i },
  { name: "Weibo", regex: /(?:www\.)?weibo\.com/i },
  { name: "Telegram", regex: /(?:www\.)?(?:t\.me|telegram\.me)/i },
  { name: "Imgur", regex: /(?:www\.)?imgur\.com/i }
];
